import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk, Arsenal_SC } from "next/font/google"; // Added Arsenal_SC
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Jaini } from "next/font/google";
import "./globals.css";
import SmoothCursor from "@/components/SmoothCursor";

const jaini = Jaini({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-jaini",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

// Added Arsenal_SC configuration
const arsenalSC = Arsenal_SC({
  variable: "--font-arsenal-sc",
  subsets: ["latin"],
  weight: ["400", "700"], // Add weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght@100..700,0..1&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&family=Plus+Jakarta+Sans:wght@400;500;600&family=Instrument+Serif&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${jaini.variable} ${geistMono.variable} ${spaceGrotesk.variable} ${arsenalSC.variable} antialiased bg-[#131313] text-white`}
      >
        <Navbar />
        <main className="min-h-screen ">
          <SmoothCursor />
       
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}

